### PR TITLE
Sync with current moose/framework/contrib/hit

### PR DESCRIPTION
**Pull request by hugary1995**
This is a blind override from the current moose/framework/contrib/hit

### CODE REVIEW

**Comment by hugary1995** [comment]
Hold on until I make sure this can work with NEML2.

**Comment by hugary1995** [comment]
Also preserved commit history and credits.

**Comment by hugary1995** [comment]
`diff -qr $HOME/projects/hit $HOME/projects/moose/framework/contrib/hit` shows
```
Only in /home/thu/projects/hit: .git
Only in /home/thu/projects/moose/framework/contrib/hit: .libs
Only in /home/thu/projects/hit: LICENSE
Files /home/thu/projects/hit/src/hit/hit.cpp and /home/thu/projects/moose/framework/contrib/hit/src/hit/hit.cpp differ
Only in /home/thu/projects/moose/framework/contrib/hit: test
```

The `hit.cpp`s diff only in trailing white spaces.

**Review by loganharbour — APPROVED** [review]

**Comment by loganharbour** [comment]
Thanks for getting to this. I'd like one day to be able to actually test it independently, but until then it's hard to keep it separate :(

**Pull request merged**
